service: memendous

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-2
  environment:
    IMAGES_DIR: ./images/
    TEXT_SIZE: 50
    TEXT_PADDING: 40

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  meme:
    handler: handler.meme
    layers: arn:aws:lambda:us-east-2:512794413931:layer:pillow:1
    events:
      - http:
          path: /
          method: get
